# .github/workflows/example-workflow.yml

name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Composite Action
        uses: ./.github/actions/my-composite-action
        with:
          greeting: 'Hi'
          name: 'John Doe'

      - name: Print Greeting
        run: echo "OutputMessage: ${{ steps.use-composite.outputs.output-message }}"
